apiVersion: v1
kind: ConfigMap
metadata:
  name: tim-configuration
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |
                app:
                    version: ${version}
                datasources:
                    mariadb:
                        jdbcUrl: jdbc:mariadb://localhost:3306/tim
                        maxLifetime: 1200000
                        maximumPoolSize: 10
                        minimumIdle: 1
                        password: password
                        poolName: MariaHikari
                        username: flexways
                oauth:
                    sign_key: 123
                rest:
                    flexways:
                        url: http://localhost:8080/services
                soap:
                    TimFlexways:
                        url: http://localhost:8088/mockTimFlexwaysMockBinding?wsdl
                    flexways:
                        authentication:
                            counter: 8
                            currency: EUR
                            locale: de
                            password: Flexways
                            timezone: UTC
                            username: peter.faltin
                    getVoyageLegs:
                        url: http://localhost:8088/mockGetVoyageLegsBinding?wsdl
                spring:
                    datasource:
                        driver-class-name: org.mariadb.jdbc.Driver
                        jndi-name: java:jboss/datasources/TimDataSource
                    jpa:
                        format-sql: false
                        properties:
                            hibernate:
                                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                        show-sql: false
                    profiles:
                        default: local
                version: 123
